### ISSUE TITLE
appSubscriptionCreate  was not working 

### ISSUE THREAD

**Issue by sanjay-ios-io** [kinngh/learning-shopify-app#2]
@kinngh  your code was really great to start building  shopify. i done the setup and all now when I do the  Subscribe your merchant to a recurring subscription plan.  ** Subscribe**  it will call the get API but i can not see the **Active Subscriptions**

**Comment by kinngh** [comment]
Can you add in more details like screenshots, console logs, etc?

**Comment by sanjay-ios-io** [comment]
@kinngh   please find the  screenshot i can't see the any console log

![Screenshot from 2022-08-16 15-12-37](https://user-images.githubusercontent.com/110609906/184849400-45455f02-7454-485b-941d-54740a44eab7.png)
![Screenshot from 2022-08-16 15-11-57](https://user-images.githubusercontent.com/110609906/184849411-e48f2ee2-53fd-4a7e-b765-4fc5a7a079e8.png)
![Screenshot from 2022-08-16 15-15-22](https://user-images.githubusercontent.com/110609906/184849825-7af2a248-1e06-4cb0-a0e8-bab741fcf211.png)

** no any error on console** 
![Screenshot from 2022-08-16 15-16-03](https://user-images.githubusercontent.com/110609906/184849944-08741fab-ec95-4b24-b570-01c4eae359b7.png)

**Comment by kinngh** [comment]
Do you get to this screen before heading over to active subscriptions?

![Screen Shot 2022-08-16 at 3 34 49 PM](https://user-images.githubusercontent.com/773555/184853736-62998d16-19af-4ef1-b592-2248d78b414c.png)

**Comment by sanjay-ios-io** [comment]
No I did not get this Screen and no any error log on console 
![image](https://user-images.githubusercontent.com/110609906/184854536-d805a1c2-43ef-4ef5-ae4d-c18f1870d546.png)
 you can see the response was null plan active

**Comment by kinngh** [comment]
...you need to wait for redirection to happen. If it just shows "redirecting" and not redirecting you, run in `npm run dev` mode and not `npm run start`

**Comment by sanjay-ios-io** [comment]
yes run with `npm run dev'

referee the app  now it show the status Redirecting

**Comment by kinngh** [comment]
Then I'm guessing it's a browser issue. Try with Chrome, if not, ping me on Twitter and we can hop on a screen share

**Comment by sanjay-ios-io** [comment]
yes i am using the chrome i try with private windows also

**Comment by kinngh** [comment]
message me on twitter so we can hop on screenshare and I can see what's up with this
